AWSTemplateFormatVersion: 2010-09-09
Resources:
  # SQS
  CustomerOtpQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: customer-otp-queue
  CustomerRegisterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: customer-register-queue

  # SNS topics
  CustomerOtpTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: customer-otp-topic
  CustomerRegisterTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: customer-register-topic

  # Subscriptions
  CustomerOtpSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt CustomerOtpQueue.Arn
      TopicArn: !GetAtt CustomerOtpTopic.TopicArn
  CustomerRegisterSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt CustomerRegisterQueue.Arn
      TopicArn: !GetAtt CustomerRegisterTopic.TopicArn