version: '3.1'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_local
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shop