version: '3.8'
services:

  dbserver:
    image: mysql:8.0
    container_name: shop_mysql_test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=shop

  redis:
    restart: always
    image: redis:alpine
    container_name: shop_redis_test
    ports:
      - '6379:6379'
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379