version: '3.8'
services:
  api:
    build:
      context: .
      target: local
    container_name: "mcshop_api"
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - redis
      - localstack
      - rabbitmq

  localstack:
    container_name: "mcshop_localstack"
    image: localstack/localstack:3.2.0
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - LOCALSTACK_HOST=localstack
      - SERVICES=secretsmanager
      - AWS_DEFAULT_REGION=ap-southeast-1
    volumes:
      - "./data/localstack/init:/etc/localstack/init/ready.d"
      - "./data/tmp/localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mysql:
    image: mysql:8.0
    container_name: "mcshop_mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
      - MYSQL_DATABASE=mcshop
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
      - ./data/mysql/init:/docker-entrypoint-initdb.d

  redis:
    restart: always
    image: redis
    container_name: "mcshop_redis"
    ports:
        - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql_data:
  mysql_config: