version: '3.8'
services:
  server:
    build:
      context: .
      target: local
    container_name: shop_server_local
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - dbserver
      - redis

  dbserver:
    image: mysql:8.0
    env_file:
      - .env
    container_name: shop_mysql_local
    ports:
      - "${DB_SHOP_PORT}:${DB_SHOP_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=${DB_SHOP_USERNAME}
      - MYSQL_PASSWORD=${DB_SHOP_PASSWORD}
      - MYSQL_DATABASE=${DB_SHOP_DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  redis:
    restart: always
    image: redis:alpine
    env_file:
      - .env
    container_name: shop_redis_local
    ports:
        - "${REDIS_SHOP_PORT}:${REDIS_SHOP_PORT}"

volumes:
  mysql_data:
  mysql_config: