version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=shop
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"