version: '3.8'
services:
  server:
    build:
      context: .
      target: development
    container_name: shop_server_local
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://db/shop
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: shop_mysql_local
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=local
      - MYSQL_PASSWORD=changemeinprod!
      - MYSQL_DATABASE=shop
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

volumes:
  mysql_data:
  mysql_config: