version: '3.8'
services:

  db:
    image: mysql:8.0
    container_name: shop_mysql_test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=shop
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  redis:
    restart: always
    image: redis:alpine
    container_name: shop_redis_test
    ports:
      - '6379:6379'

volumes:
  mysql_data:
  mysql_config: